### ISSUE TITLE
Removing current user can produce 403 HTTP responses

### ISSUE THREAD

**Issue by frafra** [moovida/GSS#6]
I logged in as "god", added a new admin account and removed the current user. That makes the admin interface not working anymore, which is a good thing, but from a user experience perspective it could be better to trigger a logout automatically.

This is a minor issue in my opinion, but I am writing that here just for completeness' sake.

**Comment by moovida** [comment]
Good point. This might even be the best moment for these issues.

**Comment by moovida** [comment]
Ok, logout is not triggered if the user is the one being removed.
