### ISSUE TITLE
//upload not found

### ISSUE THREAD

**Issue by frafra** [moovida/GSS#8]
I set a URL like `https://myserver/` in SMASH and I discovered that the trailing slash triggers a `POST //upload 404 Not Found`. 

This issue can be solved by changing SMASH or GSS or both, actually. I decided to report it here as `/` and `//` are considered to be equivalent usually.

Section "7.4.7. GSS Settings" of the SMASH documentation shows the URL without the trailing slash, which is correct.

**Comment by moovida** [comment]
That is odd. It seems to not be handled on the server side. Do you have a possibility to check if the call comes to the server? It might be javalin not accepting it.

**Comment by frafra** [comment]
I have a monitoring tool on the server which intercepts the various HTTP requests, and I clearly see a `POST //upload`. I think that is javalin not handling this case.

**Comment by moovida** [comment]
ok, thanks

**Comment by moovida** [comment]
fixed in smash.
